SELECT TID_PLAN_NO, 
  PPComponent || '_' || SUBSTR(nonPPComponent, 1, LENGTH(nonPPComponent) - INSTR(REVERSE(nonPPComponent),'~'))  || 
  CASE 
    WHEN INSTR(nonPPComponent,'~') > 0 THEN '_' || SUBSTR(nonPPComponent, INSTR(nonPPComponent,'~')+1, LENGTH(nonPPComponent) - INSTR(nonPPComponent,'~')) 
    ELSE '' 
  END AS ReverseSPI,
  STD_PARCEL_ID
  
FROM 
  (
  SELECT VTFOL_FOLIO_DTL.FOLIO_TYPE_CODE,
    VTFOL_FOLIO_DTL.TID_PLAN_NO,
    VTLAN_LAND_DTL.STD_PARCEL_ID,
    INSTR(VTLAN_LAND_DTL.STD_PARCEL_ID, 'PP') as PPLoc,
    SUBSTR(
      VTLAN_LAND_DTL.STD_PARCEL_ID, INSTR(VTLAN_LAND_DTL.STD_PARCEL_ID, 'PP')) as PPComponent,
    SUBSTR(
      VTLAN_LAND_DTL.STD_PARCEL_ID, 1, INSTR(VTLAN_LAND_DTL.STD_PARCEL_ID, 'PP')-2) as nonPPComponent
  FROM VTFOL_FOLPAR_XREF
  INNER JOIN VTFOL_FOLIO_DTL
  ON VTFOL_FOLPAR_XREF.FOLIO_REF = VTFOL_FOLIO_DTL.FOLIO_REF
  INNER JOIN VTLAN_LAND_DTL
  ON VTFOL_FOLPAR_XREF.LAND_PARCEL_ID   = VTLAN_LAND_DTL.LAND_PARCEL_ID
  WHERE VTFOL_FOLIO_DTL.FOLIO_TYPE_CODE = 'CROWN'
  )
