/* Number rnage control */
INSERT INTO VTNUM_RGE_CTL (NO_TYPE_CODE, RANGE_START, RANGE_END, CURRENT_FLAG, CHECK_DIGIT_FLAG)  SELECT 'MI',1,MAX(to_number(regexp_replace(DLNG_NO, '[^0-9]+', ''))) ,'N','Y' FROM  VTDLG_DEALING_DTL WHERE DLNG_NO LIKE 'MI%';
INSERT INTO VTNUM_RGE_CTL (NO_TYPE_CODE, RANGE_START, RANGE_END, CURRENT_FLAG, CHECK_DIGIT_FLAG)  VALUES('CD',1,999999,'Y','Y');
UPDATE  VTNUM_NUM_HDR SET NEXT_AVAIL_NO = (SELECT RANGE_END FROM VTNUM_RGE_CTL WHERE NO_TYPE_CODE = 'MI') WHERE NO_TYPE_CODE = 'MI';
